version: '3.7'

services:

  web:
    build: ../web_front_end
    container_name: web
    restart: always
    expose:
    - "3000"
    command: ["npm", "start"]

  nginx:
    build: .
    container_name: nginx
    restart: always
    ports:
      - 80:80
    depends_on:
      - web