version: '3.7'

services:

  web:
    build: ../web_front_end
    container_name: web
    restart: always
    expose:
    - "3000"
    command: ["npm", "start"]

  spotify:
    build: ../spotify_service
    container_name: spotify
    restart: always
    command: gunicorn --bind 0.0.0.0:5000 run:app
    expose:
      - 5000
    env_file:
      - ../spotify_service/.env

  nginx:
    build: .
    container_name: nginx
    restart: always
    ports:
      - 80:80
    depends_on:
      - web